# Generated by Django 5.2.7 on 2026-01-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dreams',
            old_name='carrer',
            new_name='career',
        ),
    ]
