# Generated by Django 5.2.7 on 2026-01-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_carrer_dreams_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='dustbin_dreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream', models.TextField(max_length=2000)),
                ('career', models.CharField(blank=True, max_length=200, null=True)),
                ('effort', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dreams',
            name='career',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dreams',
            name='effort',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
