# Generated by Django 5.2.7 on 2026-01-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_dustbin_dreams_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreams',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
